<?php
$beauty_helper = $this->beautyTransform();
?>

<script type="application/javascript" src="js/viewDatabase.js"></script>

<div align="left" style="width:63%;">
<table style="width: 100%; border: 1px solid black">
<tr><td>
<h4>Select table that you want to view:</h4>
</td></tr>
<tr><td align="center">
<select id="tableSelect">
	<option>Table</option>
	<?php foreach ($this->tableList as $table) : ?>
		<option><?=$table?></option>
	<?php endforeach; ?>

</select>
</td></tr>
<tr><td>
<h4>OR select logfile that you want to view:</h4>
</td></tr>
<tr><td align="center">
<select id="logFileSelect">

	<option>Logfile</option>
	<?php foreach ($this->logFiles as $logFile) : ?>
		<option><?=$logFile?></option>
	<?php endforeach; ?>

</select>
</td></tr>
</table>

<table id="tableData" style="width:100%">


	<?php foreach ($this->tableList as $table): ?>
		<tr><td align="center" style="width:100px">
		<table id=<?='"'.$table.'"'?> class="database_table" style="display:none">
		<tr>
			<?php for($i = 0; $i < count($this->keyRecords); $i++) : ?>
			<?php foreach ($this->keyRecords[$i] as $key) :?>
			<th>
				<?=$key?>
			</th>
			<?php endforeach;?>
			<?php endfor; ?>
			
		</tr>
		
		<?php for($i = 0; $i < count($this->tableRecords); $i++) : ?>
		<?php foreach($this->tableRecords[$i] as $record) :?>
			<tr>
				<?php foreach ($record as $field) :?>
					<td>
					<?php
						$result = $beauty_helper->makePrettyValue($field);
						echo $result;
					?>
					</td>
				<?php endforeach; ?>
			</tr>
		<?php endforeach;?>
		</table></td></tr>
			<?php endfor; ?>
		<?php endforeach; ?>


	<?php foreach ($this->logFilesPathes as $key => $logFilePath): ?>
		<tr><td align="center" style="width:100px">
		<table id=<?='"'.$this->logFiles[$key].'LF"'?> class="database_table" style="display:none">
		<tr>
			<th>
				Records:
			</th>
			
		</tr>
		<?php for($i = 0; $i < count($this->logRecords); $i++) : ?>
		<?php foreach ($this->logRecords[$i] as $record) :?>
			<tr>
				<td>
					<?php 
					$result = $beauty_helper->makePrettyValue($record);
					echo $result;
					 ?>
				</td>
			</tr>
		<?php endforeach;?>
		<?php endfor; ?>
		</table></td></tr>
	<?php endforeach; ?>

</table>
</div>