<div id="deldiv">
		<p>
			<span>Do you really want to delete all products</span><br />
			<form method="post" id="delform">
			<input type="text" name="confirm_password" placeholder="Confirm your password"/>
			<input type="submit" name="yes" id="yes" value="Yes" class="btn btn-primary btn-sm"/><br />
			</form>
			<input type="submit" name="no" id="no" value="No" class="btn btn-primary btn-sm"/>
		</p>
</div>