<?php echo $this->prod_response; ?>
   <?php if ( $this->session->isLogged === true ) : ?>
       <div id="product_message"><?= $this->product_message[0]; ?></div>
        <div class="row">
            <div class="add_product_form">
                <h4>Adding new product:</h4>

                <form method="post" id="form-product">
                    <p><input type="text" name="name" required placeholder="name"/>
                    <input type="text" name="description" required placeholder="description"/>
                    <input type="text" id="price_input" name="price" required placeholder="price"/>
                    <input type="submit" name="add" value="Add" class="btn btn-primary btn-sm"/>
                    </p>
                </form>
                
               <p id="q"><input type="text" name="product-search" id="product-search" placeholder="Search for product"/></p>
               
               
              <form method="post" id="delete-form">
                    <input type="submit" name="delete-all" value="Delete all products" class="btn btn-primary btn-sm"/>
                </form>
                
                <div class="load_deldiv">
                	
                </div>
               
            </div>
        </div>
		<span id="block_message">Only digit and a point separator are allowed for typing in price field.</span>
        <form method="post">
            <table class="products_table" id="old_prod">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Price</th>
                    <th></th>
                </tr>
                </thead>
                <?php for ($i = 0; $i < count($this->products); $i++) : ?>
                    <tr>
                        <td><?= $this->escape($this->products[$i]['name']) ?></td>
                        <td><?= $this->escape($this->products[$i]['description']) ?></td>
                        <td><?= $this->escape((float)$this->products[$i]['price']) ?></td>
                        <td><a href="<?="single-product?product_id={$this->products[$i]['id']}"; ?>" class="btn btn-info pull-right">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </a></td>
                    </tr>


                <?php endfor; ?>
            </table>
        </form>
        
        
                <form method="post">
            <table class="new_products_table products_table">
                <thead id="new_thead">
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Price</th>
                    <th></th>
                </tr>
                </thead>

				
            </table>
        </form>
        
        
    <?php else : ?>
        <div class="row center-row">
            <div class="center" id="hello">
                <h1 id="hello-text">Hi, please sign in to continue...</h1>
            </div>
        </div>
    <?php endif; ?>
    
	<script type="application/javascript" src="js/price_blocker.js"></script>
	<script type="application/javascript" src="js/search-product.js"></script>
	<script type="application/javascript" src="js/del-products.js"></script>