
   <?php if ( $this->session->isLogged === true ) : ?>
       <div id="product_message"><?= $this->product_message[0]; ?></div>
        <div class="row">
            <div class="add_product_form">
                <h4>Adding new product:</h4>

                <form method="post">
                    <p><input type="text" name="name" required placeholder="name"/>
                    <input type="text" name="description" required placeholder="description"/>
                    <input type="text" name="price" required placeholder="price"/>
                    <input type="submit" name="add" value="Add" class="btn btn-primary btn-sm"/></p>
                </form>
            </div>
        </div>

        <form method="post">
            <table class="products_table">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Price</th>
                    <th></th>
                </tr>
                </thead>
                <?php for ($i = 0; $i < count($this->products); $i++) : ?>
                    <tr>
                        <td><?= $this->escape($this->products[$i]['name']) ?></td>
                        <td><?= $this->escape($this->products[$i]['description']) ?></td>
                        <td><?= $this->escape((float)$this->products[$i]['price']) ?></td>
                        <td><a href="<?="single-product?product_id={$this->products[$i]['id']}"; ?>" class="btn btn-info pull-right">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </a></td>
                    </tr>


                <?php endfor; ?>
            </table>
        </form>
    <?php else : ?>
        <div class="row center-row">
            <div class="center" id="hello">
                <h1 id="center-text">Hi, please sign in to continue...</h1>
            </div>
        </div>
    <?php endif; ?>