<!-- Sidebar -->
<?php if ( $this->session->isLogged === true ) : ?>
    <ul class="sidebar-nav">
        <li class="sidebar-brand">
            <a href="#">
                Routes
            </a>
        </li>

    <?php
    $routes = $this->router->getRoutes();
    foreach ($routes as $route => $value) : ?>
        <li>
            <a
            <?php if ($route == substr($this->url(), 1)) : ?>style="<?="display: none"?>"
            <?php endif; ?>

            <?php if (($this->url() == '/') && ($route == 'default')) : ?>style="<?="display: none"?>"
            <?php endif; ?>
            href="<?=$route?>"><?=$route?></a>
        </li>
    <?php endforeach; ?>
    </ul>
<?php endif; ?>
<!-- /#sidebar -->