<!-- Sidebar -->
<!--<div id="sidebar-wrapper">-->
<?php if ( $this->session->isLogged === true ) : ?>
    <ul class="sidebar-nav">
        <li class="sidebar-brand">
            <a href="#">
                Panel
            </a>
        </li>
        <li>
            <a href="#">Link</a>
        </li>
        <li>
            <a href="#">Link</a>
        </li>
        <li>
            <a href="#">Link</a>
        </li>
        <li>
            <a href="#">Link</a>
        </li>
        <li>
            <a href="#">Link</a>
        </li>
        <li>
            <a href="#">Link</a>
        </li>
        <li>
            <a href="#">Link</a>
        </li>

    </ul>
<?php endif; ?>
<!--</div>-->
<!-- /#sidebar-wrapper -->