

<?php if(!$this->response['deleted']) : ?>
<form id="update_form" class="add_product_form" method="POST">
	<span>Name of Good</span><br />
	<?php if(is_null($this->name)) : ?>
	<input type="text" name="name" value="<?= $this->escape($this->product_info[0]['name']); ?>" /><br />
	<?php else : ?>
	<input type="text" name="name" value="<?= $this->escape($this->name) ?>" /><br />
	<?php endif; ?>
	<span>Description</span><br />
	<?php if(is_null($this->description)) : ?>
	<input type="text" name="description" value="<?= $this->escape($this->product_info[0]['description']); ?>" /><br />
	<?php else : ?>
	<input type="text" name="description" value="<?= $this->escape($this->description); ?>" /><br />
	<?php endif; ?>
	<span>Price of Good</span><br />
	<?php if(is_null($this->price)) : ?>
	<input type="text" name="price" value="<?= $this->escape($this->product_info[0]['price']); ?>" /><br />
	<?php else : ?>
	<input type="text" name="price" value="<?= $this->escape($this->price); ?>" /><br />
	<?php endif; ?>
	<br />
	<button name="update" class="btn btn-primary">Update</button>
</form>



<form id="delete_form" class="add_product_form" method="POST">
	<button name="delete" class="btn btn-primary">Delete</button>
</form>
<?php endif; ?>

<div id="message">
	<?php
		ob_start();
		echo $this->s_data;
		ob_end_flush();
	?>
</div>

<?php if(!$this->response['deleted']) : ?>
	<form method="POST" action="index" class="add_product_form">
		<button class="btn btn-primary">Back to the billing page</button>
	</form>
<?php endif; ?>


<?php

if($this->response['deleted'])	header('Refresh: '.$this->pause.'; URL=index');

?>

